### ISSUE TITLE
JSONSchema Requirements with Generics and Dates

### ISSUE THREAD

**Issue by iamwyza** [cyrilletuzi/angular-async-local-storage#136]
Now that JSONSchema is required, there are a number of issues I run into.  The biggest one is that generic type parameters are vastly more difficult to do.  

For example, I have this interface that I used prior to version 8.  This no longer will work because JSONSchema is required and within that, the schema won't allow you to have an type of object with no properties defined.

```ts
export interface CacheEntry<T> {
    data: T;
    cachedOn: Date;
    expiresOn: Date;
}
```

There needs to be a way to handle generic typed objects in the schema if schema is mandatory. 

Dates are also broken with this as well as Date isn't a valid JSONSchema type, but it was being stored before with no issue.

**Comment by cyrilletuzi** [comment]
Thanks for your feedback.

> Now that JSONSchema is required

That's not true, you can see that the JSONSchema param is optional. To be accurate, it's just that now, for TypeScript, if you don't provide a JSON schema, you'll get the `unknown` type instead, because indeed, as it's client-side storage that could be altered, you're not sure at all of what you get.

But be aware that:
- you can still do your own validation (by yourself or via another lib),
- while strongly not recommended, you can still get the pre-v8 behavior by forcing TypeScript:
```typescript
this.storageMap.get('test').subscribe((data) => {
  const unsafeData = data as string;
});
```

> Date was being stored before with no issue.

Not true eitheir. To be accurate, special objects like Date, Map and Set work well if stored in `indexedDB`. But if your app is sometimes in the scenarios where `localStorage` is used as a fallback (see the [browsers support guide](https://github.com/cyrilletuzi/angular-async-local-storage/blob/master/docs/BROWSERS_SUPPORT.md)), it won't work as they can't be serialized (see the [serialization guide](https://github.com/cyrilletuzi/angular-async-local-storage/blob/master/docs/SERIALIZATION.md)).

So the recommended way to store a date is (I'll add it to the doc):
```typescript
const someDate = new Date('2019-07-19');

/* Writing */
this.storageMap.set('date', someDate.toJSON()).subscribe();

/* Reading */
this.storageMap.get<string>('date', { type: 'string' }).pipe(
  map((dateJSON) => new Date(dateJSON)),
).subscribe((date) => {});
```

Adding options in the lib to manage some special objects could be added, but it would require some design (and some time).

> There needs to be a way to handle generic typed objects

```typescript
function cacheEntrySchema(dataSchema: JSONSchema): JSONSchema {
  return {
    type: 'object',
    properties: {
      data: dataSchema,
      cachedIn: { type: 'string' },
      expiresOn: { type: 'string' },
    }
  }
};

const someDataCacheEntrySchema = cacheEntrySchema({
  type: 'object',
  properties: {
    hello: { type: 'string' },
    world: { type: 'string' },
  }
});
```

I'll close the issue as the questions are answered, but I'll add a new one later about the possible enhancement for special objects.

**Comment by cyrilletuzi** [comment]
I created #137 for enhancement for `Date` and  other special objects.

I also added
- a chapter on custom validation in the validation guide
- a chapter on how to store `Date` safely in the serialization guide
