### ISSUE TITLE
Is it truly async?

### ISSUE THREAD

**Issue by iget-master** [cyrilletuzi/angular-async-local-storage#17]
Reading this piece of code:

https://github.com/cyrilletuzi/angular-async-local-storage/blob/a0ec30e64601b05f6b8d456f5d82ba87d3ebbf5c/src/lib/src/service/databases/localstorage-database.ts#L15-L37

It doesn't seem to be async actually, since this line will block the returning of the observable:

    const unparsedData = this.localStorage.getItem(key);

You are returning an observable of the existing response from unparsedData. If for some reason browser takes too long to give a response to `LocalStorage.getItem()` method, all the execution from here will be blocked until it's ready.

**Comment by cyrilletuzi** [comment]
Please read the README before posting an issue, as the answer is in it : 

> Even so, IE9 is supported but use native localStorage as a fallback, so internal operations are synchronous (the public API remains asynchronous-like).

And if you want to check the code, really check it. You would see in the NgModule that only IE9 uses this code, which is unlikely a browser in which you'll need this lib. All other browsers use `IndexedDB` which is async.

I included IE9 support with `localStorage` as a fallback because it wasn't difficult to do so. But as that's not the first time I get this unfriendly question, I may remove it in next major release.

**Comment by NarHakobyan** [comment]
It's not async, here is an example
https://stackblitz.com/edit/typescript-afvlzr?file=index.ts
