### ISSUE TITLE
Docs: Let us know that this can't be used for sessionStorage like functionality

### ISSUE THREAD

**Issue by xsegrity** [cyrilletuzi/angular-async-local-storage#212]
Maybe consider putting a note at the top of the docs to indicate that this cannot be used for "sessionStorage". I realize (now) that this isn't this library's intended use but I had to read through all the docs (and one of your closed issues) before coming to that realization because of the name of the library. It might save someone else the time if they are looking for a sessionStorage/localStorage wrapper library.

As a side note, this looks like a great library and I might use it down the road for some other stuff.

**Comment by cyrilletuzi** [comment]
I don't think the lib is misleading: it's about `localStorage` (which is persistent) from the beginning of the README. It's even the name of the lib.

The real issue is a common misconception about the role of local storage in applications. But you're right about the fact it's a frequent research (there were indeed previous issues and nearly all the students I have in trainings do the same mistake), so I added a mention about expiration in the README with a link to [a full page of explanation](https://github.com/cyrilletuzi/angular-async-local-storage/blob/master/docs/EXPIRATION.md).
