### ISSUE TITLE
Get data in sync

### ISSUE THREAD

**Issue by kareljan** [cyrilletuzi/angular-async-local-storage#3]
Is there a way to get the data synchronized rather than async? sometimes you want is to be in sync.

thanks

**Comment by cyrilletuzi** [comment]
If you want synchronous data, then the native localStorage API should be enough for most cases. The purpose of this module is to be asynchronous. Once the data has been stored asynchronously in IndexedDB, it will have to be read asynchronously too from IndexedDB.

At some point I thought about an option to load all data on init, and then provide a synchronous function to get data from this static storage, instead of re-querying asynchronously IndexdedDB each time. Speed advantage, but memory disadvantage.

Can you provide a use case where it would be worth it ?

**Comment by cyrilletuzi** [comment]
Closing, as there as been no answer and I don't see a performant way to do this feature.

**Comment by cyrilletuzi** [comment]
For info, since v5.2, there is now 3 new methods:
- `setItemSubscribe()`
- `removeItemSubscribe()`
- `clearSubscribe()`

**It's still async**, but it avoids to do the `subscribe()` manually when the callback is not needed.
