### ISSUE TITLE
Feature: unknown type for getItem calls without a validation

### ISSUE THREAD

**Issue by cyrilletuzi** [cyrilletuzi/angular-async-local-storage#49]
**The issue**

Any local storage (`localStorage`, `indexedDb`...) is not secure by nature, as the client can forge the value (intentionally or not). It can cause security issues and errors (as the received data type may not be what you expected). Then, any data coming from local storage should be checked before used.

That's why v5 of this lib introduced a new option for `getItem()` to validate the data against a JSON schema. But for now it's optional (to not break with previous versions and to let users use their own validation system), which is bad.

**The proposition**

The proposition is to require a validation. It is know possible with the new type `unknown` in TypeScript >= 3, supported by Angular >= 7.

It would mean:
- no change for users already doing a validation via the JSON schema option of the lib:

```typescript
// Before and after v7.0.0-beta.1
this.localStorage.getItem<string>('test', { schema: { type: 'string' } }).subscribe((result) => {
  result; // type: string
  result.substr(0, 2); // OK
});
```

- `getItem()` calls with no schema option would now return `unknown` (instead of `any`), forcing users to validate the data. For example:

```typescript
// Before v7.0.0-beta.1
this.localStorage.getItem('test').subscribe((result) => {
  result; // type: any
  result.substr(0, 2); // Bad but compilation OK
});

// With v7.0.0-beta.1
this.localStorage.getItem('test').subscribe((result) => {

  result; // type: unknown
  result.substr(0, 2); // Compilation error

  if (typeof result === 'string') {
    result; // type: string
    result.substr(0, 2); // OK
  }

});
```

Pros:
- Good for security!
- Good for avoiding errors (which are not tolerable in an app)!

Cons:
- As it would be managed on the TypeScript level, I don't see a way to provide a runtime option to keep the old behavior, so it would be an important breaking change. But the new errors that would be raised would be very legitimate, as they mean something was done the wrong way before.

You can test with: `npm install @ngx-pwa/local-storage@beta`

Feedback welcome!

**Comment by cyrilletuzi** [comment]
@juristr @alexpanov @nikolalukovic @dherges @FrankiePo @beeman @joeskeen @rajd90 @alignsoft @sylvaingirardbe @darthmolen @feldmarv @doughlass @hannesrohde @venoby @supdegrave @LowieDelneste @Pato91 @elkozmon @pinalbhatt @todian @palmtreefrb @atiris @Gorniv @glebmachine 

Hi everyone, as users of the lib, I would like some community feedback before making my decision on this one:
- do you think the proposition is a good idea?
- do you already validate all your data?
- if not, would it be a huge work to change?

**Comment by sylvaingirardbe** [comment]
Sounds like a good idea. I'm not validating atm and it wouldn't be a huge change.

**Comment by atiris** [comment]
Likewise, I do not use data validation now, because it's optional, it would not be complicated to do it, and if it made me use the exact types, it's just better for me.
Everything that increases the level of type control I see as a plus.

But, I would expect these two types of listing to be equivalent, but they are not.

``` typescript
this.localStorage.getItem('a', { schema: { type: 'number' } })
    .subscribe(a => this.a = a); // OK
this.localStorage.getItem<number>('nu')
    .subscribe(a => this.a = a); // ERR: Type 'unknown' is not assignable to type 'number'
```

Will it be possible in v.7 to use a shorter code like: `.getItem<string>(...)` instead of full schema definition? Sorry, if I do not do the validation properly (it probably should not be used as an equivalent), I have not used it yet.

**Comment by cyrilletuzi** [comment]
@atiris Unfortunately, it's not possible, otherwise it would have been done in the first place instead of the JSON schema option.

I've already planned to add a point in the documentation about this, to avoid confusion:
- the JSON schema is used to validate local storage data, as it can only be done at runtime (TypeScript only happens at compilation time, so `getItem<number>` can't do any real validation) ;
- the cast (`getItem<number>`) is only here so you don't end up with `any` while you already validated the data (and it's why it's optional).

So `getItem<number>` alone is impossible. The other way (ie.: auto-detecting the type from the JSON schema) could be a thing someday, but I'm not sure it's possible with current TypeScript features.

**Comment by alignsoft** [comment]
Currently I encrypt the values saved into local storage depending on a build flag, so my structure varies - if encryption is on, the Key is a string, and the Value is an object {crypt: string}. However if it's off, the value varies widely depending on what data I'm storing, and creating validation patterns for each use case in my applications would create a large amount of effort to solve a problem I'm not concerned with, and specifically because the non-encrypted form is generally used during development, not production, which would mean writing additional code simply to support visibility of data during development.

Unless I'm missing something, or misunderstanding how this validation would work, and how loose the patterns could potentially be.

As I don't have any use for stronger validation myself, and I'm a little concerned adding it will increase the overhead in my application to support it, my preference would be for this validation to be optional.

**Comment by cyrilletuzi** [comment]
@alignsoft 
1. Do we agree that even if your data is encrypted, the object stored in local storage can be forged, so you still need to check that it's a `{ crypt: string }` object?

2. How do you manage on the same `getItem` call that sometimes it's a `{ crypt: string }` object and some other time something else? Doesn't it mean you are already doing manual validation (like `typeof`...)?

3. Would a `getUnsafeItem()` (which would be an easy refactoring) a reasonable option?

**Comment by alignsoft** [comment]
I pass all returned data through a function that tests `data.hasOwnProperty('crypt')`, and then decrypt and forward, or forward the unencrypted data depending on the result.

getUnsafeItem() would be a very reasonable option, and would make clear from name exactly what was happening and be a potential flag for tightening the validation in key areas in the future.

**Comment by cyrilletuzi** [comment]
@alignsoft Then you're already doing validation by yourself and you shouldn't be impacted by this change!

If it was not clear, the change does not force to use the library validation system, you can use your own (like `typeof`, `hasOwnProperty` or any other third-party lib). It's the second example in my initial post.

I'll do a few tests to check it goes well with all kind of native validation functions.

But I think I'll keep the `getUnsafeItem()` idea nevertheless.

**Comment by cyrilletuzi** [comment]
Thanks everyone for your feedback.

A new v7.0.0-beta.2 has been released. There will be 4 solutions:
- required validation by default:
  - either via the JSON schema option of the lib
  - or via manual/custom validation
- temporary deferring the upgrade as v6 of the lib is compatible with Angular 7
- `getUnsafeItem()` added for corner cases

To assist users with this important change, documentation has been fully revamped and completed. You can preview this in the [`ng7` branch](https://github.com/cyrilletuzi/angular-async-local-storage/tree/ng7), in particular the [migration guide to v7](https://github.com/cyrilletuzi/angular-async-local-storage/blob/ng7/docs/MIGRATION_TO_V7.md), where everything about this issue is explained in details.

If some of you have some time to test the v7, feedback would be much appreciated:
`npm install @ngx-pwa/local-storage@next`

**Comment by cyrilletuzi** [comment]
Released in v7.0.0.

**Comment by cyrilletuzi** [comment]
Hi @alignsoft,

I'm preparing a full refactoring of the lib for v8, so I was curious how things went with v7 and required validation in your special case. Especially, do you have to use `getUnsafeItem()`? I'm considering to remove this method in v8.

**Comment by alignsoft** [comment]
I'm using encryption on everything I'm storing in localstorage, so my validation looks like this:

```
const schema: JSONSchemaObject = {
  properties: {
    crypt: { type: 'string' } as JSONSchemaString,
  },
  required: ['crypt']
};

```
Where the object stored is always 'key','crypt:object-or-data-encrypted-as-string-after-json-stringify', so that works perfectly without requiring me to use getUnsafeItem. In some instances, I am saving simple values that don't require encrypting, and those require different validation. It's been easier for me to encrypt them and not bother with different validation patterns, but that's just laziness on my part - there's no reason I couldn't switch them.

**Comment by cyrilletuzi** [comment]
@alignsoft Thanks for your feedback. I'll remove `getUnsafeItem()` in v8 then.
