### ISSUE TITLE
Unwrap value in `indexedDb`?

### ISSUE THREAD

**Issue by cyrilletuzi** [cyrilletuzi/angular-async-local-storage#67]
Follow up of #65.

Currently, when storing in `indexedDb`, values are wrapped in this structure: `{ value: ... }`. It's totally OK inside the lib, but can cause (rare) interoperability issues.

Need investigation to check if unwrapping is possible, as it could lead to major breaking change.

**Comment by Ruluk** [comment]
So, to follow up from #65, what if you consider the object with ONLY the `value` key as a candidate to unwrap? If it has any other key, it is probably a raw object.

In fact, you could do the opposite and start saving a new key to indicate that you were the one that saved it. So, say, if the key `angularAsyncLocalStorage: true` exists, then it was surely this lib. Otherwise, fall back to analysis of current data.

Another idea (that may work alongside the previous one) can be to add a configuration option for your lib to indicate a predefined `getItem` behavior. Possible values could be, e.g, `'always_raw', 'always_unwrap', 'default'`.

**Comment by cyrilletuzi** [comment]
Your first solution would still be a problem for objects with just `value` (which is a common pattern).

The last idea will probably be the good one.

**Comment by cyrilletuzi** [comment]
Fixed by #82, which will be available in v8.
