### ISSUE TITLE
can i use this library for asynchronously call API even if the local storage has data, have attached a PNG.

### ISSUE THREAD

**Issue by arunkmr25** [cyrilletuzi/angular-async-local-storage#99]
![Capture](https://user-images.githubusercontent.com/11206794/56159687-f6d65500-5fe2-11e9-9bc5-6ef00b585ca8.PNG)

**Comment by arunkmr25** [comment]
Anybody?

**Comment by cyrilletuzi** [comment]
Hi @arunkmr25, thanks for your interest in the lib. Unfortunately I am currently very busy and I have not much time for support requests.

You can ask your company if some consulting would be OK, otherwise I suggest you to ask your question on Stackoverflow. It's a RxJS question, not an issue specific to this lib.

I'll close this issue for house keeping purpopose.
